#!/usr/bin/env node
// rock-paper-scissors-game/src/scripts/generate-icons.mjs
// Run: node src/scripts/generate-icons.mjs

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const imagesDir = path.resolve(__dirname, "../images");
const outputFile = path.join(imagesDir, "index.ts");

function toPascalCase(filename) {
  const base = filename.replace(/\.svg$/i, "");
  return base
    .split(/[-_\s.]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/**
 * Adds a viewBox derived from width/height if the SVG doesn't have one.
 * - Leaves width/height attributes as-is — CSS sizing handles the rest.
 */
function normalizeSvgViewBox(svg) {
  if (/\bviewBox\s*=/.test(svg)) return svg;

  const widthMatch = svg.match(/\bwidth="([\d.]+)(?:px)?"/);
  const heightMatch = svg.match(/\bheight="([\d.]+)(?:px)?"/);

  if (!widthMatch || !heightMatch) {
    // eslint-disable-next-line no-console
    console.warn("Cannot derive viewBox — missing width/height on <svg>");
    return svg;
  }

  const width = widthMatch[1];
  const height = heightMatch[1];

  return svg.replace(/<svg\b/, `<svg viewBox="0 0 ${width} ${height}"`);
}

/**
 * Replaces literal fill/stroke colors with currentColor.
 */
function normalizeSvgColors(svg) {
  const skip = (value) => value === "none" || value.startsWith("url(");

  svg = svg.replace(/(fill|stroke)="([^"]*)"/g, (match, attr, value) =>
    skip(value) ? match : `${attr}="currentColor"`,
  );

  svg = svg.replace(/style="([^"]*)"/g, (match, styleContent) => {
    const updated = styleContent.replace(
      /(fill|stroke)\s*:\s*([^;]+)/g,
      (m, prop, value) => {
        const v = value.trim();
        return skip(v) ? m : `${prop}:currentColor`;
      },
    );
    return `style="${updated}"`;
  });

  return svg;
}

const svgFiles = readdirSync(imagesDir)
  .filter((file) => file.toLowerCase().endsWith(".svg"))
  .sort();

// Normalize colors for icons
for (const file of svgFiles) {
  const filePath = path.join(imagesDir, file);
  const original = readFileSync(filePath, "utf-8");
  let normalized = normalizeSvgViewBox(original);

  if (file.toLowerCase().startsWith("icon-")) {
    normalized = normalizeSvgColors(normalized);
  }

  if (normalized !== original) {
    writeFileSync(filePath, normalized, "utf-8");
  }
}

const entries = svgFiles.map((file) => ({
  file,
  componentName: toPascalCase(file),
}));

const imports = entries
  .map(
    ({ file, componentName }) =>
      `import ${componentName} from "./${file}?react";`,
  )
  .join("\n");

const iconsObject = entries
  .map(({ componentName }) => `  ${componentName},`)
  .join("\n");

const output = `// AUTO-GENERATED by src/scripts/generate-icons.mjs — do not edit by hand.

${imports}

export const Icons = {
${iconsObject}
};
`;

writeFileSync(outputFile, output, "utf-8");

// eslint-disable-next-line no-console
console.log(`Generated ${entries.length} icon(s).`);
