// AUTO-GENERATED by src/scripts/generate-icons.mjs — do not edit by hand.

import BgPentagon from "./bg-pentagon.svg?react";
import BgTriangle from "./bg-triangle.svg?react";
import IconClose from "./icon-close.svg?react";
import IconLizard from "./icon-lizard.svg?react";
import IconLoader from "./icon-loader.svg?react";
import IconMenu from "./icon-menu.svg?react";
import IconPaper from "./icon-paper.svg?react";
import IconRanking from "./icon-ranking.svg?react";
import IconRock from "./icon-rock.svg?react";
import IconScissors from "./icon-scissors.svg?react";
import IconSpock from "./icon-spock.svg?react";
import ImageRulesBonus from "./image-rules-bonus.svg?react";
import ImageRules from "./image-rules.svg?react";
import Leaderboard1 from "./leaderboard-1.svg?react";
import Leaderboard2 from "./leaderboard-2.svg?react";
import Leaderboard3 from "./leaderboard-3.svg?react";
import LeaderboardEmpty from "./leaderboard-empty.svg?react";
import LeaderboardError from "./leaderboard-error.svg?react";
import LogoBonus from "./logo-bonus.svg?react";
import Logo from "./logo.svg?react";
import Pointer from "./pointer.svg?react";
import Spinner from "./spinner.svg?react";
import Youtube from "./youtube.svg?react";

export const Icons = {
  BgPentagon,
  BgTriangle,
  IconClose,
  IconLizard,
  IconLoader,
  IconMenu,
  IconPaper,
  IconRanking,
  IconRock,
  IconScissors,
  IconSpock,
  ImageRulesBonus,
  ImageRules,
  Leaderboard1,
  Leaderboard2,
  Leaderboard3,
  LeaderboardEmpty,
  LeaderboardError,
  LogoBonus,
  Logo,
  Pointer,
  Spinner,
  Youtube,
};
